    <footer class="boc-black-bg">
        
        <!-- Bottom bar navigation -->
        <nav class="boc-grid-container boc-3-cols">
            <div>
                <h4>Contact Us</h4>
                <ul>
                    <li><a href="contact-us.php">Contact Us</a></li>
                    <li><a href="privacy-policy.php">Privacy Policy</a></li>
                    <li><a href="terms-and-conditions.php">Terms & Conditions</a></li>
                </ul>     
            </div>
            <div>
                <h4>Customer Service</h4>
                <ul>
                    <li><a href="returns.php">Returns</a></li>
                    <li><a href="delivery.php">Delivery</a></li>
                    <li><a href="complaints.php">Complaints</a></li>
                </ul>
            </div>
            <div>
                <h4>Account</h4>
                <ul>
                    <li><a href="account.php">My Account</a></li>
                    <li><a href="order-history.php">Order History</a></li>
                    <li><a href="wishlist.php">Wishlist</a></li>
                </ul>  
            </div>
        </nav>
    

        <div class="boc-white-bg boc-center">
            <!-- Footer bar with copyright -->
            Copyright &copy; 2020 Barry's Bargain Books
        </div>
    </footer>
    <div id="toast"><!-- generated by javascript --></div>